### PR TITLE
[MSCRIPTING-1] Allow scripting in files

### PR DESCRIPTION
**Pull request by rpopov**
[MSCRIPTING-1] Squashed all commits from MSCRIPTING-1 branch - see the [corresponding pull request](https://github.com/apache/maven-scripting-plugin/pull/1)

### CODE REVIEW

**Comment by eolivelli** [comment]
I hope we will be able to merge this soon.
Sorry for this taking so long

**Comment by rpopov** [comment]
JIRA is already set up. Please merge.

**Comment by eolivelli** [comment]
Sure. Will do tomorrow

**Comment by eolivelli** [comment]
Sorry. I did have time to commit.
I will try to be back on this as soon as possible.
I will also try to prepare for a first release of the plugin

**Comment by eolivelli** [comment]
@rpopov I have pushed this change to Apache repository 
https://github.com/apache/maven-scripting-plugin/tree/MSCRIPTING-1

This triggered the official "pre-commit" job, you can see the logs here:
https://builds.apache.org/job/maven-box/job/maven-scripting-plugin/job/MSCRIPTING-1

When the build ends I will commit.

I have reworked the commit message a little, in order to have a better git history

**Comment by eolivelli** [comment]
@rpopov  committed as b20e1c3dc647ddc3e522f286cc6252321509dd96

I will setup for a first release
You can follow up Maven dev@ mailing list about the release

cc @rfscholte

**Comment by jira-importer** [comment]
Resolve #41

**Pull request closed without merging**
